### ISSUE TITLE
Option to reduce the Speed

### ISSUE THREAD

**Issue by RaZok17** [Pada-js/Zerk-Fast-Rampage#3]
Just an idea, cuz lets be honest anyone that uses it at the current speed is just gonna get banned sooner or later. The "Delay" in config doesnt seem to do anything in that regard either.

**Comment by Pada-js** [comment]
ok, will try something soon!

**Comment by Pada-js** [comment]
it's done!

!zfr delay {value} - set the delay value(millisecond) before canceling the animation.

!zfr mode hit|delay - switch mode to cancel the animation. "hit" cancel animation on hit. "delay" cancel the animation after a delay
